from linked_list import Element
from linked_list import LinkedList
my_list = LinkedList()
my_list.append(Element(5))
my_list.append(Element(56))
my_list.append(Element(90))
my_list.append(Element(80))
my_list.append(Element(60))
my_list.append(Element(63))
my_list.append(Element(70))
my_list.append(Element(89))
my_list.append(Element(91))
# my_list.print()
# print()
# sliced_list = my_list.slice(2, 5)
# my_second_list = LinkedList()
# my_second_list.append(Element(4))
# my_second_list.append(Element(69))
# my_second_list.append(Element(98))
# my_second_list.append(Element(8))
# my_second_list.print()
# my_list.print()
# print()
# sliced_list.print()
sliced_list = my_list.slice(3, 5)
spliced_list = my_list.splice(3, 5)
my_list.print()
print()
sliced_list.print()
print()
spliced_list.print()
print()
deep_spliced_list = my_list.deep_splice(2, 5)
deep_spliced_list.print()
print()
# print(spliced_list.head)
# print()
# print(getattr(spliced_list.head, 'value'))

is_exist_element = my_list.is_exists(Element(91))
print()
print(is_exist_element)
find_element = my_list.find(3)
print()
print(find_element)
